% solver_hot_reverse.m
% Replicates Figure 18: Cold coil parametric study WITH reversed hot coil

model = model_data();
tank = tank_data();

% Set baseline Reynolds numbers
model.Reh = 6.48e4; 
model.Rec = 1.73e4;

% Setup coil geometry for Figure 18
model.l_h = 2.0; % Hot coil is 2m long (covers entire tank)
model.x_h = 0.0; % Hot coil starts at the top (0m)
model.l_c = 1.0; % Cold coil is 1m long

% Define the three configurations for the cold coil location
xc_configs = [0.1, 0.5, 0.9];
config_labels = {'x_c = 0.1m - 1.1m (Top)', 'x_c = 0.5m - 1.5m (Middle)', 'x_c = 0.9m - 1.9m (Bottom)'};

% Time settings for the mixing loop
t_end = 10 * 3600; % 10 hours to reach steady state
dt_step = 60;

Results_T_out = cell(length(xc_configs), 1);
node_vol = (pi*(tank.D^2)/4) * model.dx;

figure('Position', [100, 100, 800, 500]);
hold on; box on;

markers = {'d-', '*-', 'o-'};
h_sim = zeros(1, length(xc_configs));

for k = 1:length(xc_configs)
    disp(['Running simulation for cold coil at ', config_labels{k}]);
    
    model.x_c = xc_configs(k);
    
    T_in = ones(model.N, 1) * model.T0;
    Th_in = ones(model.N, 1) * model.T0;
    Tc_in = ones(model.N, 1) * model.T0;
    T_current = [T_in; Th_in; Tc_in];
    
    t_current = 0;
    
    % Buoyancy Node Mixing Loop using reverse_hot_hex
    while t_current < t_end
        t_span = [t_current, t_current + dt_step];
        
        % Using the user's reverse_hot_hex!
        [~, T_step] = ode15s(@(t, T_state) reverse_hot_hex(t, T_state, model, tank), t_span, T_current);
        
        T_latest = T_step(end, :)';
        T_tank = T_latest(1:model.N); 
        
        % Buoyancy Mixing (Crucial because hot water enters at the bottom and rises!)
        for sweep = 1:model.N 
            for i = 2:model.N
                if T_tank(i) > T_tank(i-1)
                    prop = water_properties(T_tank(i));
                    prop_1 = water_properties(T_tank(i-1));
                    m = node_vol * prop.rho;
                    m1 = node_vol * prop_1.rho;
                    
                    T_mixed = (m*T_tank(i) + m1*T_tank(i-1))/(m + m1);
                    T_tank(i) = T_mixed;
                    T_tank(i-1) = T_mixed;
                end
            end
        end
        
        T_latest(1:model.N) = T_tank;
        T_current = T_latest;
        t_current = t_current + dt_step;
    end
    
    % Extract steady state
    T_tank_steady = T_current(1:model.N)';
    T_star_steady = (T_tank_steady - 300) / 100;
    x_H = (0.5 : 1 : model.N) / model.N; 
    
    idx_markers = 1:round(model.N/10):model.N;
    
    h_sim(k) = plot(x_H, T_star_steady, markers{k}, 'LineWidth', 1.5, ...
         'MarkerIndices', idx_markers, 'MarkerSize', 8, 'MarkerFaceColor', 'none', ...
         'Color', 'k');
end

xlabel('x/H', 'FontSize', 14);
ylabel('T^*', 'FontSize', 14);
set(gca, 'XTick', 0:0.2:1, 'YTick', 0:0.2:1.0, 'FontSize', 14);
axis([0 1 0 1.0]); 

lgd = legend(h_sim, config_labels);
set(lgd, 'Location', 'northeast', 'Box', 'off', 'FontSize', 12);
title('Fig 18: Hot Coil Reversed (Bottom-Up) Parametric Study', 'FontSize', 14);

% NOTE: I am omitting the R^2 calculations from your previous file because those 
% reference data points were for Fig 16 (Normal Flow) and won't match the flattened 
% profiles generated by the reversed flow + buoyancy mixing!

hold off;
disp('Figure 18 generated successfully!');
